USE [PT_STORE_YYPT_LC_0718]
GO

/****** Object:  Table [dbo].[DIM_BGSZ_BGSJY]    Script Date: 02/24/2017 13:53:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DIM_BGSZ_BGSJY](
	[BGDM] [varchar](36) NOT NULL,
	[SJYDM] [varchar](36) NOT NULL,
	[SJYMC] [varchar](36) NULL,
	[SQLYJ] [varchar](2000) NULL,
PRIMARY KEY CLUSTERED 
(
	[SJYDM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

